### ISSUE TITLE
Deepin Linux

### ISSUE THREAD

**Issue by 21wmd** [xtomcom/mirrorrequest#1]
To Whom It May Concern,

I’m Azlar fromDeepin Team. This email is to ask help for mirror support from your site. Would you like to do us a favor to mirror our distribution? So that people around the world could benefit from faster connection and download speed. 

Deepin is a Linux distribution originated from China, which aims to provide a real beautiful and user-friendly experience.

There are many custom and quality applications in Deepin, such as Deepin Software Center, DMusic (a powerful and good-looking audio player), DSnapshot (a handy screenshot tool) and so on.  More information, please refer to:

Official Site: http://www.deepin.org
Worldwide Code Address: https://github.com/linuxdeepin

Early reply will be warmly appreciated. 

Thanks and best regards

**Comment by import-yuefeng** [comment]
HK, US mirror 完成同步.
