### ISSUE TITLE
openEuler镜像源的申请加入镜像站

### ISSUE THREAD

**Issue by zhang-jian-jun** [xtomcom/mirrorrequest#10]
上游源（官方镜像）的地址
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler

镜像简介
我们是来自于openEuler[ https://openeuler.org/zh/ ]开源操作系统社区的基础设施团队, openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展。当前openEuler社区有自己的发布仓库[ https://repo.openeuler.org/ ]，想咨询下能否在你们的镜像源上面支持openEuler社区的镜像呢？多谢！

我们提供openEuler镜像同步指令如下:
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
镜像大小:
多个版本共600G

openEuler社区基础设施团队
[1]: https://openeuler.org/zh/
[2]: https://repo.openeuler.org/

**Comment by Showfom** [comment]
我们香港的 mirror 没那么多硬盘了，暂时无法加新的 repo 请见谅

**Comment by zhang-jian-jun** [comment]
好的，谢谢哈，希望以后能加上

**Comment by Showfom** [comment]
https://mirrors.xtom.de/openeuler/
https://mirrors.xtom.ee/openeuler/
https://mirrors.xtom.jp/openeuler/

同步中

**Comment by nicliuqi** [comment]
@Showfom Hello，请问xtom方便为openeuler添加其他地区的repo吗，如
https://mirrors.xtom.com
https://mirrors.xtom.com.hk 等

**Comment by zhang-jian-jun** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
