### ISSUE TITLE
添加CircleLinux的镜像（Add CircleLinux Mirror to Mirrors ）

### ISSUE THREAD

**Issue by James6xie** [xtomcom/mirrorrequest#11]
- Project website:  https://cclinux.org/

- Parent mirror:  https://mirror.cclinux.org/  

- Setup Instructions: https://wiki.cclinux.org/en/team/infra/add-mirrorr-repo

- Description: Circle Linux 是国际化社区驱动的开源软件，使命在与努力专注于围绕 Linux 平台提供更强大的开源生态。
提供企业级、生产环境就绪的 Linux 发行版。 立足中国希望可以服务全球喜欢我们的用户。

- Reason: 
   - No mirrors for this distro in Europe yet 
   - Europe User want to speed up to use circleilnux  and report issues  https://bugzilla.cclinux.org/show_bug.cgi?id=9

- 上游地址与镜像方法 (How to mirror)

    rsync -avh rsync://msync.cclinux.org/circle/pub/

**Comment by bella485** [comment]
@Showfom if you europe mirrors had some space , please consider circlelinux, europe users report us mirrors very slow.
thanks a lot.

**Comment by Showfom** [comment]
Started syncing

https://mirrors.xtom.de/circle/

**Comment by bella485** [comment]
> Started syncing
> 
> https://mirrors.xtom.de/circle/

Best  Wishes !

Good News For CircleLinux europe developers and users.

Thanks your help and Thank xtom mirrors.
