### ISSUE TITLE
Rocky Linux mirror request

### ISSUE THREAD

**Issue by leeyc0** [xtomcom/mirrorrequest#12]
Project website: https://rockylinux.org/
Mirror requirement: https://docs.rockylinux.org/guides/mirror_management/add_mirror_manager/
Summary: Rocky Linux is a downstream clone of Red Hat Linux. Red Hat killed CentOS as a downstream clone of RHEL and instead only maintain CentOS stream which is a **upstream testing bed** of RHEL. This project is created to re-fill the gap. Currently there is no Hong Kong mirror, adding a Hong Kong mirror will serve the public.

**Comment by Showfom** [comment]
https://mirrors.xtom.jp/rocky/
https://mirrors.xtom.de/rocky/
https://mirrors.xtom.ee/rocky/

We already had it in other countries, for HK mirror, there's no plan to add more repos at this time.

**Comment by Showfom** [comment]
Rocky Linux has been added to all of our mirror servers.
