### ISSUE TITLE
Make Fedora mirror official

### ISSUE THREAD

**Issue by proletarius101** [xtomcom/mirrorrequest#14]
xTom provides mirror for Fedora and it's [up-to-date](https://mirror.xtom.com.hk/fedora/updates/36/Everything/state). But your mirror is not listed in https://admin.fedoraproject.org/mirrormanager//map/mirrors.html such that it can be distributed by the Fedora mirror manager. Are there any plans to make this mirror available to the public in the official Fedora mirror list? 

https://fedoraproject.org/wiki/Infrastructure/Mirroring#Signing_up

**Comment by Showfom** [comment]
Added
