### ISSUE TITLE
Clear Linux* Repository

### ISSUE THREAD

**Issue by NextGenOP** [xtomcom/mirrorrequest#15]
Clear Linux* is Linux OS developed by Intel. But their repo isn't stable and sometime it slow and no one has mirror it yet. I found this from Ubuntu mirror archive. Thanks for your mirror services
Official repository:
https://download.clearlinux.org
https://cdn.download.clearlinux.org
https://cdn-alt.download.clearlinux.org

**Comment by Showfom** [comment]
We do not have plan to add mirror for Clear Linux.
