### ISSUE TITLE
Please sign the Release files in Debian mirrors

### ISSUE THREAD

**Issue by ValentinLiu15** [xtomcom/mirrorrequest#19]
apt now requiring a signed `InRelease` `Release` file.

**Comment by Showfom** [comment]
What do you mean? Can you show logs?

**Comment by ValentinLiu15** [comment]
Sorry for that I can not provide the log immediately. I will post the log later.

The apt showed that
`E: The repository 'http://mirror.xtom.com/debian bullseye InRelease' is not signed. `
(something I typed may wrong, but that's the mean)

Those happened while executing apt update command.

**Comment by Showfom** [comment]
This usually occurs when we're syncing from the upstream. You can try again in a few hours.
