### ISSUE TITLE
cdnjs 镜像申请

### ISSUE THREAD

**Issue by gaoyifan** [xtomcom/mirrorrequest#2]
@import-yuefeng  有空加个镜像哈~

上游：git://github.com/cdnjs/cdnjs.git
脚本：https://github.com/ustclug/ustcmirror-images#gitsync
背景： @Showfom 计划建一个 cdnjs 的镜像服务器组。mirrors 从官方仓库使用 git 协议同步，并提供 rsync 服务。 镜像服务器组用 rsync 从 mirrors 同步。

**Comment by import-yuefeng** [comment]
好的, 近期同deepin完成镜像同步

**Comment by import-yuefeng** [comment]
HK, US mirror 完成同步.
