### ISSUE TITLE
Manjaro Linux

### ISSUE THREAD

**Issue by black18x** [xtomcom/mirrorrequest#3]
To Whom It May Concern,

I’m Manjaro Linux user. This email is to ask help for mirror support from your site. Would you like to do us a favor to mirror our distribution? So that people around the world could benefit from faster connection and download speed.

Manjaro is a Linux distribution originated from Germany, which aims to provide a real beautiful and user-friendly experience.

Official Site: http://manjaro.org
Worldwide Code Address: https://gitlab.manjaro.org

Early reply will be warmly appreciated.

Thanks and best regards

**Comment by Showfom** [comment]
Location: Duesseldorf, Germany

```
http://mirrors.xtom.de/manjaro/
https://mirrors.xtom.de/manjaro/
rsync://mirrors.xtom.de/manjaro/
```

Location: Tallinn, Estonia

```
http://mirrors.xtom.ee/manjaro/
https://mirrors.xtom.ee/manjaro/
rsync://mirrors.xtom.ee/manjaro/
```

Location: Osaka, Japan

```
http://mirrors.xtom.jp/manjaro/
https://mirrors.xtom.jp/manjaro/
rsync://mirrors.xtom.jp/manjaro/
```
