### ISSUE TITLE
Kali Linux 軟件倉庫及ISO镜像申请

### ISSUE THREAD

**Issue by OodavidsinoO** [xtomcom/mirrorrequest#4]
**上游源:** http://http.kali.org/
**镜像设定方法:** https://docs.kali.org/community/kali-linux-mirrors
**Kali Linux背景:** Kali Linux 为网络安全而生，专为网络工程师和发烧友提供一个合适的测试环境
**原因:** 在亚洲地区没有可靠高速的Kali 源

**Comment by Showfom** [comment]
Sync started

https://mirrors.xtom.de/kali/
https://mirrors.xtom.de/kali-images/

https://mirrors.xtom.ee/kali/
https://mirrors.xtom.ee/kali-images/

https://mirrors.xtom.jp/kali/
https://mirrors.xtom.jp/kali-images/
