### ISSUE TITLE
Arch Linux ARM request

### ISSUE THREAD

**Issue by isaackwan** [xtomcom/mirrorrequest#5]
* 上游源（官方鏡像）的地址: https://archlinuxarm.org/about/mirrors
* 該項目的介紹: A fork of Arch Linux - designed for ARM SBC's - eg Raspberry Pi
* 為什麼希望添加該鏡像: There is only 1 PoP in Singapore - it would be really useful to have a second Asian presence

**Comment by Showfom** [comment]
https://mirrors.xtom.jp/archlinux-arm/
