### ISSUE TITLE
Ubuntu Kylin iso镜像申请

### ISSUE THREAD

**Issue by liumin0322** [xtomcom/mirrorrequest#6]
官方网址：http://www.ubuntukylin.com
镜像同步方法：RSYNC_PASSWORD="user"  /usr/bin/rsync -azHv --delete --port=8873  --progress  user@service.ubuntukylin.com::rsync   ~/data				
rsync同步地址: user@service.ubuntukylin.com::rsync /data 
申请理由：希望提供更多高速镜像站

**Comment by Showfom** [comment]
Seems the rsync server is down, I sent an email to them.

**Comment by Showfom** [comment]
联系不上，所以暂时不做 Ubuntu Kylin 的 mirror 了
