### ISSUE TITLE
请求贵镜像站参加 mirrorz

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [xtomcom/mirrorrequest#7]
网站demo: https://mirrorz.org
项目地址: https://github.com/tuna/mirrorz

该项目意在为用户与镜像管理员提供统一的前端，方便用户查找镜像，同时方便管理员查看与对比服务器状态。

参加该项目只需要网站后端生成相关格式的数据。

**Comment by Showfom** [comment]
已加入
