### ISSUE TITLE
Add AlmaLinux to mirror

### ISSUE THREAD

**Issue by ckykenken** [xtomcom/mirrorrequest#8]
Project website: https://almalinux.org/
Parent mirror: https://repo.almalinux.org/ (setup instructions: https://wiki.almalinux.org/Mirrors.html)
Description: Launched with the code-name Project Lenix, AlmaLinux OS is an open-source, community-driven project that intends to fill the gap left by the demise of the CentOS stable release. AlmaLinux OS is a 1:1 binary compatible fork of RHEL® 8 and it is built by the creators of the established CloudLinux OS.
Reason: No mirrors for this distro in Hong Kong yet

**Comment by Showfom** [comment]
We are do not have enough HDD space in Hong Kong mirror server, will consider in the future.

AlmaLinux had been added in our Germany server

https://mirrors.xtom.de/almalinux/

**Comment by Showfom** [comment]
AlmaLinux has been added to all of our mirror servers.
